### ISSUE TITLE
autoRefreshToken doesn't work

### ISSUE THREAD

**Issue by nuurcodes** [supabase/supabase-js#178]
# Bug report

## Describe the bug

After initialising supabase client with
```
createClient(supabaseUrl, supabaseKey, {
  localStorage: AsyncStorage as any,
  autoRefreshToken: true
});
```
and setting the JWT expiry to 60 (seconds) on the supabase dashboard, the token does not refresh after 60 seconds have elapsed. Oddly enough, setting the JWT expiry to anything less than 60 triggers the token refresh but it constantly updates without waiting for expiry

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Setup RN project (I used expo bare)
2. Set JWT expiry to 60
2. Add supabase auth state listener
3. Sign in
4. Wait for refresh token to update (doesn't update)

## Expected behavior

The token should refresh after the expiry time set on the supabase dashboard

## System information

- OS: macOS
- Version of supabase-js: 1.11.14
- Version of Node.js: 16.1.0

**Comment by awalias** [comment]
hey @nuurcodes thanks for the issue, could you please test if you can reproduce with the latest supabase-js version v1.13.1

**Comment by nuurcodes** [comment]
@awalias Setting the JWT expiry to anything less than 60 still causes the accessToken to update in a loop

When I set the JWT expiry to 60, I was expecting the accessToken to automatically update every 60 seconds but it doesn't. I've tried logging `supabase.auth.session()` and also listening to `onAuthStateChange`

**Comment by churichard** [comment]
Having the same issue here. I'm constantly needing to log back into my app, even though I've set the expiration date to be a week long and have `autoRefreshToken` set to true. It seems like I need to re-enter my credentials even if the token is not actually expired (i.e. I need to re-enter my credentials even though a week has not passed since the last time I did it). This happens both on localhost and on my production website.

If `autoRefreshToken` is true, I would expect the token to be automatically refreshed without needing to enter my credentials again. In other words, if I've logged in once, I should stay logged in unless I've explicitly logged out or cleared my cookies/cache.

**Comment by heauton** [comment]
Shouldn't this be on by default? https://github.com/supabase/supabase-js/blob/master/src/SupabaseClient.ts#L11-L12

I still see this issue on 1.15.0.

**Comment by b2m9** [comment]
Sorry to dig out an old issue, but are we sure this is fixed? Despite initializing the Supabase client with `autoRefreshToken: true` I have to double check `session.expires_at` and initiate `supabase.auth.refreshSession()` manually throughout my app. (on version 1.28.2)

There isn't much documentation on how `autoRefreshToken` is supposed to work. But judging from the questions in the discussions section, I'm not the only one who is having trouble letting Supabase refresh expired JWTs.

**Comment by bangdragon** [comment]
> 

How you catch session expires and and initiate supabase.auth.refreshSession() manually. Thanks

**Comment by bangdragon** [comment]
> Sorry to dig out an old issue, but are we sure this is fixed? Despite initializing the Supabase client with `autoRefreshToken: true` I have to double check `session.expires_at` and initiate `supabase.auth.refreshSession()` manually throughout my app. (on version 1.28.2)
> 
> There isn't much documentation on how `autoRefreshToken` is supposed to work. But judging from the questions in the discussions section, I'm not the only one who is having trouble letting Supabase refresh expired JWTs.

How you catch session expires and and initiate supabase.auth.refreshSession() manually. Thanks

**Comment by ARMATAV** [comment]
Still broken. `autoRefresh` setting does nothing to actually trigger a refresh and you will keep setting the error in perpetuity until you manually reload the page.

<img width="447" alt="image" src="https://user-images.githubusercontent.com/2433203/178385213-d57f9a4e-fe09-4d41-ae29-6226eb10a35b.png">

**Comment by edgarsilva** [comment]
Yeah this seems to still be happening, at least when running Supabase locally for development, working on a React Native app using Expo ->

```
LOG  SB Res --> {"data": {"session": null}, "error": [AuthApiError: Invalid Refresh Token]}
```

Trying to figure out how long

**Comment by erickreutz** [comment]
Can confirm this is also happening for me.
